export const COURSE_TYPE_LOAD_REQUEST = "COURSE_TYPE_LOAD_REQUEST";
export const COURSE_TYPE_LOAD_SUCCESS = "COURSE_TYPE_LOAD_SUCCESS";
export const COURSE_TYPE_LOAD_FAIL = "COURSE_TYPE_LOAD_FAIL";
export const COURSE_TYPE_LOAD_RESET = "COURSE_TYPE_LOAD_RESET";

export const CREATE_COURSE_TYPE_REQUEST = "CREATE_COURSE_TYPE_REQUEST";
export const CREATE_COURSE_TYPE_SUCCESS = "CREATE_COURSE_TYPE_SUCCESS";
export const CREATE_COURSE_TYPE_FAIL = "CREATE_COURSE_TYPE_FAIL";
export const CREATE_COURSE_TYPE_RESET = "CREATE_COURSE_TYPE_RESET";


export const DELETE_COURSE_TYPE_REQUEST = "DELETE_COURSE_TYPE_REQUEST";
export const DELETE_COURSE_TYPE_SUCCESS = "DELETE_COURSE_TYPE_SUCCESS";
export const DELETE_COURSE_TYPE_FAIL = "DELETE_COURSE_TYPE_FAIL";
export const DELETE_COURSE_TYPE_RESET = "DELETE_COURSE_TYPE_RESET";

export const EDIT_COURSE_TYPE_REQUEST = "EDIT_COURSE_TYPE_REQUEST";
export const EDIT_COURSE_TYPE_SUCCESS = "EDIT_COURSE_TYPE_SUCCESS";
export const EDIT_COURSE_TYPE_FAIL = "EDIT_COURSE_TYPE_FAIL";
export const EDIT_COURSE_TYPE_RESET = "EDIT_COURSE_TYPE_RESET";