export const COURSE_LOAD_REQUEST = "COURSE_LOAD_REQUEST";
export const COURSE_LOAD_SUCCESS = "COURSE_LOAD_SUCCESS";
export const COURSE_LOAD_FAIL = "COURSE_LOAD_FAIL";
export const COURSE_LOAD_RESET = "COURSE_LOAD_RESET";

export const COURSE_LOAD_SINGLE_REQUEST = "COURSE_LOAD_SINGLE_REQUEST";
export const COURSE_LOAD_SINGLE_SUCCESS = "COURSE_LOAD_SINGLE_SUCCESS";
export const COURSE_LOAD_SINGLE_FAIL = "COURSE_LOAD_SINGLE_FAIL";
export const COURSE_LOAD_SINGLE_RESET = "COURSE_LOAD_SINGLE_RESET";

export const REGISTER_COURSE_REQUEST = "REGISTER_COURSE_REQUEST";
export const REGISTER_COURSE_SUCCESS = "REGISTER_COURSE_SUCCESS";
export const REGISTER_COURSE_FAIL = "REGISTER_COURSE_FAIL";
export const REGISTER_COURSE_RESET = "REGISTER_COURSE_RESET";

export const DELETE_COURSE_REQUEST = "DELETE_COURSE_REQUEST";
export const DELETE_COURSE_SUCCESS = "DELETE_COURSE_SUCCESS";
export const DELETE_COURSE_FAIL = "DELETE_COURSE_FAIL";
export const DELETE_COURSE_RESET = "DELETE_COURSE_RESET";

export const EDIT_COURSE_REQUEST = "EDIT_COURSE_REQUEST";
export const EDIT_COURSE_SUCCESS = "EDIT_COURSE_SUCCESS";
export const EDIT_COURSE_FAIL = "EDIT_COURSE_FAIL";
export const EDIT_COURSE_RESET = "EDIT_COURSE_RESET";